name = "short-link-server"
main = "src/index.js"
compatibility_date = "2025-09-01"

[vars]
ENVIRONMENT = "production"

[[ d1_databases ]]
binding = "DB"
database_name = "shortlink_db"
database_id = "08528f8a-8741-402f-8f43-a64a76a1cea3"

[[routes]]
pattern = "link.gjqqq.com"
custom_domain = true